import { IconPrintWrapper } from ".";

export default {
  title: "Components/IconPrintWrapper",
  component: IconPrintWrapper,

  argTypes: {
    icon: {
      options: [
        "united-states",
        "dots",
        "triangle",
        "categories",
        "returns",
        "sales",
        "stores",
        "cash",
        "people",
        "payment",
        "export",
        "view",
        "products",
        "shop",
        "print",
        "pause",
        "notification",
        "download",
        "arrow-left",
        "cancel",
        "euro-light",
        "setup",
        "warehouse",
        "search",
        "minus",
        "register",
        "stock-transfer",
        "edit",
        "user-management",
        "image",
        "question-mark",
        "settings",
        "receipt-2",
        "retrieve",
        "dinar",
        "australia",
        "date",
        "tick",
        "variant",
        "clear",
        "icon-park-solid-success",
        "percentage",
        "euro-thick",
        "sub-category",
        "increase",
        "decrease",
        "chevron-down",
        "delivery-2",
        "menu",
        "point-of-sale-1",
        "clock",
        "loyalty",
        "discount",
        "point-of-sale-2",
        "import",
        "receipt-1",
        "chevron-up",
        "password-2",
        "dashboard",
        "export-2",
        "united-kingdom",
        "hand-click",
        "delete",
        "excel",
        "payment-card",
        "inventory",
        "calculator",
        "dollar",
        "filter",
        "sell",
        "reports",
        "pound",
        "user",
        "nigeria-flag",
        "delivery-1",
        "naira",
        "required",
        "manage",
        "afghani",
        "add",
        "information",
        "password",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    icon: "united-states",
    className: {},
    iconIncrease: "/img/icon-increase-1.png",
    iconDecrease: "/img/icon-decrease-1.png",
  },
};
