import { EscrowIcons } from ".";

export default {
  title: "Components/EscrowIcons",
  component: EscrowIcons,

  argTypes: {
    icon: {
      options: [
        "dashboard",
        "completed-2",
        "loading-03",
        "activity",
        "dot-2",
        "pending",
        "cancelled-1",
        "progress-2",
        "delete",
        "tick",
        "dollar",
        "password-hide",
        "share",
        "filter",
        "swap",
        "notification",
        "arrow-up",
        "copy",
        "success",
        "deal",
        "download",
        "cancel",
        "search",
        "chevron-up",
        "progress-1",
        "cancelled-2",
        "overview",
        "chevron-down",
        "google",
        "loading-02",
        "arrow-head",
        "home",
        "dot",
        "calender",
        "apple",
        "export",
        "help",
        "PDF",
        "swap-2",
        "completed-1",
        "more",
        "password-view",
        "image",
        "rocket",
        "settings",
        "shopping-bag",
        "upload",
        "inbox",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    icon: "dashboard",
    className: {},
    iconCopy: "/img/icon-copy.png",
  },
};
