import { IconMenuWrapper } from ".";

export default {
  title: "Components/IconMenuWrapper",
  component: IconMenuWrapper,

  argTypes: {
    icon: {
      options: [
        "dashboard",
        "integration",
        "twitter",
        "mdi-chevron-down",
        "hand-click",
        "delete",
        "excel",
        "tick",
        "inventory",
        "filter",
        "variant",
        "sell",
        "optimization",
        "notification",
        "reporting",
        "mingcute-currency-nigeria-2-line",
        "youtube-filled",
        "icon-park-solid-success",
        "arrow-left",
        "cancel",
        "categories",
        "point-of-sale",
        "percentage",
        "nigeria-flag",
        "warehouse",
        "search",
        "naira",
        "sub-category",
        "facebook-2",
        "user-friendly-interface",
        "youtube-outline",
        "required",
        "sales",
        "stock-transfer",
        "stores",
        "menu",
        "dot",
        "geo-fencing",
        "conversion",
        "people",
        "add",
        "export",
        "information",
        "view",
        "facebook-1",
        "edit",
        "user-management",
        "import",
        "products",
        "image",
        "password",
        "instagram",
        "settings",
        "chevron-up",
      ],
      control: { type: "select" },
    },
  },
};

export const Default = {
  args: {
    icon: "dashboard",
    className: {},
    iconAdd: "/img/icon-add.png",
    iconTwitter: "/img/icon-twitter.png",
    iconYoutubeOutline: "/img/icon-youtube-outline.png",
    iconInstagram: "/img/icon-instagram.png",
    iconFacebook: "/img/icon-facebook-1.png",
  },
};
